
name: 部署文档

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.7.0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist

  - name: Build and Compress Artifacts
    run: |
      # 进入实际构建目录
      cd src/.vuepress/dist || exit
      
      # 获取Git短hash和当前时间
      HASH=$(echo $GITHUB_SHA | cut -c1-7)
      DATE=$(date +"%Y%m%d")
      TIME=$(date +"%H%M")
      
      # 创建zip和tar.gz压缩包
      zip -r ../Souton_Website-$HASH-$DATE-$TIME.zip .
      tar -czf ../Souton_Website-$HASH-$DATE-$TIME.tar.gz .
    
  - name: Create Release with Artifacts
    uses: softprops/action-gh-release@v1
    with:
      # 保持原有Release命名格式
      tag_name: "Releases ${{ env.HASH }} (${{ env.DATE }}-${{ env.TIME }})"
      release_name: "Releases ${{ env.HASH }} (${{ env.DATE }}-${{ env.TIME }})"
      draft: false
      prerelease: false
      files: |
        ../Souton_Website-${{ env.HASH }}-${{ env.DATE }}-${{ env.TIME }}.zip
        ../Souton_Website-${{ env.HASH }}-${{ env.DATE }}-${{ env.TIME }}.tar.gz
